require("servers.clangd")
require("servers.lua_ls")
require("servers.pyright")
require("servers.jsonls")
require("servers.react")
require("servers.tailwindcss")

vim.lsp.enable("clangd")
vim.lsp.enable("lua_ls")
vim.lsp.enable("pyright")
vim.lsp.enable("jsonls")
vim.lsp.enable("vtsls")
vim.lsp.enable("tailwindcss")
